table dim_date
	lineageTag: 5c0f3b32-9efd-46d4-8cbf-67ea1bcfcdf6
	dataCategory: Time

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 570fe9b8-43c3-4e1a-af9f-49eba3088d04
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 3f23a21a-f4ec-4ec5-8384-90f180ef493f
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 519fbe2c-4923-447b-ab74-e407bfbec03c
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 306211d5-ab85-4880-b132-5a0637331d06
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: b458665b-0b40-4975-bddc-f8e519c6eab3
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: d416e084-7f47-4dd0-a2c7-549e2462f06e
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		formatString: 0
		lineageTag: a670402a-fb05-4d14-9f93-35b3d9d0f268
		summarizeBy: sum
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: int64
		formatString: 0
		lineageTag: a8577541-fcac-4cad-b7bd-0564406f2b48
		summarizeBy: sum
		sourceColumn: fiscal_quarter

		annotation SummarizationSetBy = Automatic

	column is_weekday
		dataType: int64
		formatString: 0
		lineageTag: ecc37877-c7a7-4bc6-8b45-a40a558d73c4
		summarizeBy: sum
		sourceColumn: is_weekday

		annotation SummarizationSetBy = Automatic

	column date_key_target
		dataType: int64
		formatString: 0
		lineageTag: b6728abb-53e7-49ab-b634-47d0a070d3b8
		summarizeBy: none
		sourceColumn: date_key_target

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("D:\PBI\Chubb Assessment\dim_date.csv"),[Delimiter=",", Columns=9, QuoteStyle=QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"fiscal_year", Int64.Type}, {"fiscal_quarter", Int64.Type}, {"is_weekday", Int64.Type}}, "en-US"),
				    #"Added Custom" = Table.AddColumn(#"Changed column type", "date_key_target", each [year] * 100 + [month]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"date_key_target", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

