table fact_sales
	lineageTag: 13f64f71-ac72-411a-8e33-b29f5d441e13

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 6dde5e35-06ad-4132-a58c-6db84976fdab
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 65982709-77a3-4f55-946d-ff4333db923b
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column agent_id
		dataType: int64
		formatString: 0
		lineageTag: d0055469-114d-419c-aafd-022b8ba8e07e
		summarizeBy: none
		sourceColumn: agent_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: d295ccb9-3659-47fa-9dc0-885fa4c69666
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column ape_usd
		dataType: double
		lineageTag: ce89215e-8087-4c50-b9fc-afc0ee447c9e
		summarizeBy: sum
		sourceColumn: ape_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fyp_usd
		dataType: double
		lineageTag: b0ae6e3f-6b9a-4dd3-911a-b4b9fc647d55
		summarizeBy: sum
		sourceColumn: fyp_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column policies_issued
		dataType: int64
		formatString: 0
		lineageTag: 56ef8106-8b4c-4da8-aa1c-cf94ed3562f0
		summarizeBy: sum
		sourceColumn: policies_issued

		annotation SummarizationSetBy = Automatic

	column sale_channel
		dataType: string
		lineageTag: b502aa3e-cc91-468e-ac1b-9c3fb3f985b5
		summarizeBy: none
		sourceColumn: sale_channel

		annotation SummarizationSetBy = Automatic

	column agent_name =
			
			IF(
			    ISBLANK(RELATED(dim_agent[agent_name])),
			    "Unknown Agent",
			    RELATED(dim_agent[agent_name])
			)
		lineageTag: bbfc58de-5013-471b-8751-a318276e2788
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fact_sales = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("D:\PBI\Chubb Assessment\fact_sales.csv"),[Delimiter=",", Columns=8, QuoteStyle=QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"sale_id", Int64.Type}, {"date_key", Int64.Type}, {"agent_id", Int64.Type}, {"product_id", Int64.Type}, {"ape_usd", type number}, {"fyp_usd", type number}, {"policies_issued", Int64.Type}, {"sale_channel", type text}}, "en-US"),
				  #"Added Unknown Agents" = Table.ReplaceValue(
				    #"Changed column type",
				    each [agent_id],
				    each if List.Contains(DimAgentIds, [agent_id]) then [agent_id] else -1,
				    Replacer.ReplaceValue,
				    {"agent_id"}
				),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Unknown Agents",{{"agent_id", Int64.Type}})
				in
				  #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

