table fact_persistency
	lineageTag: e2570ce5-2a9d-4521-ad2f-4cfe3d90a46f

	column policy_id
		dataType: int64
		formatString: 0
		lineageTag: 74aacc3a-04fc-461a-a12e-225c6d993027
		summarizeBy: sum
		sourceColumn: policy_id

		annotation SummarizationSetBy = Automatic

	column agent_id
		dataType: int64
		formatString: 0
		lineageTag: 4f1792b3-482a-4835-baba-d065fb736b8c
		summarizeBy: none
		sourceColumn: agent_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: f94f4826-38df-4edd-98c9-c2f2b661381e
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column issue_date_key
		dataType: int64
		formatString: 0
		lineageTag: 3690ea32-6d59-40bd-92e9-800b0fdce77b
		summarizeBy: sum
		sourceColumn: issue_date_key

		annotation SummarizationSetBy = Automatic

	column renewal_due_date_key
		dataType: int64
		formatString: 0
		lineageTag: dcaaa21a-e4ce-4d6b-b53b-c2835c6ba718
		summarizeBy: none
		sourceColumn: renewal_due_date_key

		annotation SummarizationSetBy = Automatic

	column renewal_status
		dataType: string
		lineageTag: be8aa28e-1cb6-49ad-84ed-110b3ab90ee3
		summarizeBy: none
		sourceColumn: renewal_status

		annotation SummarizationSetBy = Automatic

	column premium_usd
		dataType: double
		lineageTag: 3c9bab94-1fcc-4139-9003-147c07e43308
		summarizeBy: sum
		sourceColumn: premium_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cohort_year =
			
			LOOKUPVALUE( dim_date[year], dim_date[date_key], fact_persistency[issue_date_key] )
		formatString: 0
		lineageTag: ccc6e926-deaf-4654-82d5-dfffe5cf84bc
		summarizeBy: none

		annotation SummarizationSetBy = User

	column renewal_year =
			
			VAR RenewalYear = LOOKUPVALUE( dim_date[year], dim_date[date_key], fact_persistency[renewal_due_date_key] )
			RETURN RenewalYear
		formatString: 0
		lineageTag: 92495318-f23c-4db8-aaf4-73ce3befdea6
		summarizeBy: none

		annotation SummarizationSetBy = User

	column years_since_issue =
			
			VAR IssueYear = LOOKUPVALUE( dim_date[year], dim_date[date_key], fact_persistency[issue_date_key] )
			VAR RenewalYear = LOOKUPVALUE( dim_date[year], dim_date[date_key], fact_persistency[renewal_due_date_key] )
			RETURN RenewalYear - IssueYear
		formatString: 0
		lineageTag: 8a514601-55c6-409e-bcbe-2af444e069a8
		summarizeBy: none

		annotation SummarizationSetBy = User

	partition fact_persistency = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("D:\PBI\Chubb Assessment\fact_persistency.csv"),[Delimiter=",", Columns=7, QuoteStyle=QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"policy_id", Int64.Type}, {"agent_id", Int64.Type}, {"product_id", Int64.Type}, {"issue_date_key", Int64.Type}, {"renewal_due_date_key", Int64.Type}, {"renewal_status", type text}, {"premium_usd", type number}}, "en-US"),
				  #"Added Unknown Agents" = Table.ReplaceValue(
				    #"Changed column type",
				    each [agent_id],
				    each if List.Contains(DimAgentIds, [agent_id]) then [agent_id] else -1,
				    Replacer.ReplaceValue,
				    {"agent_id"}
				),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Unknown Agents",{{"agent_id", Int64.Type}})
				in
				  #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

